In [2]:
import pandas as pd
import spacy
from spacy import displacy
from spacy.tokens import Doc
import numpy as np
import json

json_path = '/home/pgajo/Multitask-RFG/data/yamakata/efrc_ud.json'

with open(json_path, 'r', encoding='utf8') as f:
    data = json.load(f)

sample = data[0]

# Load the English language model
nlp = spacy.load('en_core_web_sm')

sent = sample['words']
doc = nlp(Doc(nlp.vocab, sent))

# Get the number of tokens
num_tokens = len(doc)

# Initialize an adjacency matrix of size num_tokens x num_tokens with zeros
adj_matrix = np.zeros((num_tokens, num_tokens), dtype=int)

# Populate the adjacency matrix based on dependencies with only `dobj` labels
for token in doc:
    if token.dep_ == 'dobj' and token.head != token:  # Only add for `dobj` dependencies
        adj_matrix[token.head.i, token.i] = 1  # Edge from head to token for `dobj`

# Print the adjacency matrix
print("Adjacency Matrix:")
print(adj_matrix)


Adjacency Matrix:
[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
import pandas as pd
import spacy
from spacy import displacy
from spacy.tokens import Doc
import numpy as np
import json

json_path = '/home/pgajo/Multitask-RFG/data/yamakata/efrc_ud.json'

with open(json_path, 'r', encoding='utf8') as f:
    data = json.load(f)
    
# Load the English language model
nlp = spacy.load('en_core_web_sm')
sent = data[0]['words']
doc = nlp(Doc(nlp.vocab, sent))

# Get the number of tokens
num_tokens = len(doc)

# Initialize an adjacency matrix of size num_tokens x num_tokens with zeros
adj_matrix = np.zeros((num_tokens, num_tokens), dtype=int)

# Populate the adjacency matrix based on dependencies with only `dobj` labels
for token in doc:
    if token.dep_ == 'dobj' and token.head != token:  # Only add for `dobj` dependencies
        adj_matrix[token.head.i, token.i] = 1  # Edge from head to token for `dobj`

# Print the adjacency matrix
print("Adjacency Matrix with `dobj` dependencies:")
print(adj_matrix.sum())


Adjacency Matrix with `dobj` dependencies:
3


In [5]:
adj_matrix.shape

(58, 58)

In [7]:
np.array(data[0]['sent_indices'])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# Load the English language model
nlp = spacy.load('en_core_web_sm')

# Example sent to parse
sent = "Apple's CEO Tim Cook visited the company's headquarters in Cupertino."

# Parse the sent using spaCy
doc = nlp(sent)
print(doc)

# Visualize the dependency tree with default settings
displacy.render(doc, style='dep', jupyter=True)

In [ ]:
# Load the English language model
nlp = spacy.load('en_core_web_sm')

# Example sent to parse
sent = ["Prick", "the", "potatoes", "with", "a", "fork", "several", "times", ",", "then", "rub", "potatoes", "with", "olive", "oil", ",", "sprinkle", "with", "salt", "and", "wrap", "tightly", "in", "foil", ".", "Place", "the", "potatoes", "into", "a", "slow", "cooker", ",", "cover", ",", "and", "cook", "on", "High", "for", "4", "1/2", "to", "5", "hours", ",", "or", "on", "Low", "for", "7", "1/2", "to", "8", "hours", "until", "tender", "."]
# Tokenize the sent
doc = 


# Get the number of tokens
num_tokens = len(doc)

# Initialize an empty matrix of size num_tokens x num_tokens with empty strings
label_matrix = [["" for _ in range(num_tokens)] for _ in range(num_tokens)]

# Populate the label matrix based on dependencies
for token in doc:
    if token.head != token:  # Exclude root token pointing to itself
        label_matrix[token.head.i][token.i] = token.dep_

# Convert to a DataFrame for a cleaner display
label_matrix_df = pd.DataFrame(label_matrix, columns=[token.text for token in doc], index=[token.text for token in doc])

# Print the labeled adjacency matrix
print("Labeled Adjacency Matrix:")
print(label_matrix_df)


In [ ]:
import spacy
from spacy.tokens import Doc

# Load the English language model
nlp = spacy.load('en_core_web_sm')

# Example instruction sent
# sent = "Prick the potatoes with a fork several times, then rub potatoes with olive oil, sprinkle with salt and wrap tightly in foil. Place the potatoes into a slow cooker, cover, and cook on High for 4 1/2 to 5 hours, or on Low for 7 1/2 to 8 hours until tender."
sent = ["Prick", "the", "potatoes", "with", "a", "fork", "several", "times", ",", "then", "rub", "potatoes", "with", "olive", "oil", ",", "sprinkle", "with", "salt", "and", "wrap", "tightly", "in", "foil", ".", "Place", "the", "potatoes", "into", "a", "slow", "cooker", ",", "cover", ",", "and", "cook", "on", "High", "for", "4", "1/2", "to", "5", "hours", ",", "or", "on", "Low", "for", "7", "1/2", "to", "8", "hours", "until", "tender", "."]
# Tokenize the sent
doc = Doc(nlp.vocab, sent)
doc = nlp(doc)

# Extract tokens as a list of text
tokens = [token.text for token in doc]
print(len(tokens))
